---
name: Test-Aggregate
version: 0.363
author:
  - 'Curtis "Ovid" Poe <ovid@cpan.org>'
abstract: Aggregate C<*.t> tests to make them run faster.
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::Most: 0.21
  Test::Simple: 0.94
requires:
  FindBin: 1.47
  Test::Harness: 3.09
  Test::NoWarnings: 0
recommends:
  Data::Dump::Streamer: 1.11
  Perl::Tidy: 20060614
  Test::More: 0.94
configure_requires:
  Module::Build: 0.35
provides:
  Test::Aggregate:
    file: lib/Test/Aggregate.pm
    version: 0.363
  Test::Aggregate::Base:
    file: lib/Test/Aggregate/Base.pm
    version: 0.363
  Test::Aggregate::Builder:
    file: lib/Test/Aggregate/Builder.pm
    version: 0.363
  Test::Aggregate::Nested:
    file: lib/Test/Aggregate/Nested.pm
    version: 0.363
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
