--- #YAML:1.0
name:               Test-Aggregate
version:            0.364
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    FindBin:           1.47
    Test::Harness:     3.09
    Test::Most:        0.21
    Test::NoWarnings:  0
    Test::Simple:      0.94
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
